model:
  target: cldm.cldm_coco.ControlLDM
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "jpg"
    cond_stage_key: "txt"
    control_key: "hint"
    image_size: 32 
    channels: 4
    cond_stage_trainable: false
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False
    only_mid_control: False

    control_stage_config:
      target: cldm.cldm_coco.ControlNet
      params:
        image_size: 32 
        in_channels: 4
        hint_channels: 3
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False

    unet_config:
      target: cldm.cldm_coco.ControlledUnetModel
      params:
        image_size: 32 
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False

    first_stage_config:
      target: ldm.modules.encoders.modules.IdentityEncoder

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder

data:
  target: utils.utils.DataloaderFromConfig
  params:
    batch_size: 2
    num_workers: 2
    train:
      target: utils.coco_dataset_less_vram.cocoConditionalTrain
      params:
        target_img_path: "datasets/coco/256_latents/train2017"
        flip_p: 0.5
        size: 256
    validation:
      target: utils.coco_dataset_less_vram.cocoConditionalValidation
      params:
        target_img_path: "datasets/coco/256_latents/val2017"
        flip_p: 0
        size: 256